import { Geist, Geist_Mono, Hubot_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const hubot=Hubot_Sans({
  variable:"--font-hubot",
  subsets: ["latin"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CORPORATION",
  description: "Generated by create next app",
  icons: {
    icon: "/secondlogo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${hubot.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <NavBar/> */}
        {children}
      </body>
    </html>
  );
}
